// react-18-features-examples/src/components/Navbar.js
import {Link} from 'react-router-dom'

const Navbar = () => (
  <>
    <header className="bg-dark text-white p-2">
      <div className="d-flex justify-content-between container align-items-center">
        <h2>React 18 Features</h2>
        <nav className="flex">
          <div>
            <Link to="/" className="text-white">
              {' '}
              Home
            </Link>
          </div>
        </nav>
      </div>
    </header>
  </>
)

export default Navbar

// JSCOE-132/src/Components/Navbar.svelte
<!-- Navbar using svelete Navigator -->
<script>
    import {Link} from "svelte-navigator";

</script>

<header>
    <h1>Navbar</h1>
    <nav>
      <Link to="/">Home</Link>
      <Link to="about">About</Link>
      <Link to="profile">Profile</Link>
    </nav>
</header>

<style>
    nav {
        display: flex;
    }

    nav :global(a) {
        color: #fff;
        text-decoration: none;
        padding: 5px;
    }

    header {
        display: flex;
        align-items: center;
        justify-content: space-around;
    }
</style>
